BNF ::= 左辺 ':' '=' 右辺 ';'

左辺 ::= 非終端記号

右辺 ::= 非終端記号
      | 終端記号
      | 非終端記号 右辺
      | 終端記号 右辺
      | 非終端記号 '|' 右辺
      | 終端記号 '|' 右辺

非終端記号 ::= '<' 文字列 '>' 

終端記号 ::= 文字列

文字列 ::= '"' 文字 ( ( '"' '"' )? 文字 )* '"'
         | 文字+

文字 ::= 数字
       | 英字
       | 特殊文字
       | '＄日本文字'

数字 ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

英字 ::= 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M'
       | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z'
       | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm'
       | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'

特殊文字 ::= '△' | '/' | ':' | '@' | '[' | '`' | '{' | '~'
